web/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView


urlpatterns = patterns('web.views',
	url(r'^(?P<language_slug>[a-z]{2,3})/(?P<page_slug>(\w|-)+)\.html$', 'show_page', name='show_page'),
    url(r'^(?P<language_slug>[a-z]{2,3})$', 'index', name='index'),
    url(r'^$', 'index', name='index'),
)

yugteatr/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('web.urls')),
)

web/models.py
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField


class Language(models.Model):
    name = models.SlugField(max_length=10, unique=True)
    order = models.IntegerField(null=True, blank=True) # optional order field

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return '/%s' % self.name


class Page(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    body = models.TextField(null=True, blank=True)
    language = models.ForeignKey('Language')

    url = models.CharField(max_length=200, blank=True, null=True)
    order = models.IntegerField(null=True, blank=True) # optional order field

    # parent page
    parent = models.ForeignKey('self', null=True, blank=True)

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        if self.url:
            return self.url
        else:
            return '/%s/%s.html' % (self.language, self.slug)




class Person(models.Model):
    slug = models.SlugField(max_length=50)

    photo = ThumbnailerImageField(upload_to='staff', blank=True, null=True)

    # enum type field
    PERFORMER = 1
    DESIGNER = 2
    DIRECTOR = 3
    PERSON_TYPES = (
        (PERFORMER, 'Performer'),
        (DESIGNER, 'Designer'),
        (DIRECTOR, 'Director'),
    )
    staff_type = models.IntegerField(choices=PERSON_TYPES)

    def __unicode__(self):
        return self.slug

    def get_absolute_url(self):
        return '/staff/%s' % self.slug

    class Meta:
        verbose_name = 'Staff'
        verbose_name_plural = 'Staff'


class PersonInformation(models.Model):
    language = models.ForeignKey('Language')
    person = models.ForeignKey('Person', null=True)
    name = models.CharField(max_length=50)
    about = models.TextField()

    def __unicode__(self):
        return self.name


class Play(models.Model):
    slug = models.SlugField(max_length=50)

    def __unicode__(self):
        return self.slug


class PlayPhoto(models.Model):
    title = models.CharField(max_length=50)
    photo = ThumbnailerImageField(upload_to='plays')
    play = models.ForeignKey('Play')

    def __unicode__(self):
        return self.title


class PlayInformation(models.Model):
    play = models.ForeignKey('Play')
    language = models.ForeignKey('Language')

    title = models.CharField(max_length=50)
    body = models.TextField()

    def __unicode__(self):
        return self.title


class Performance(models.Model):
    play = models.ForeignKey('Play')
    show_time = models.DateTimeField()
    
    performers = models.ManyToManyField('Person', related_name='performers')
    designers = models.ManyToManyField('Person', related_name='designers')
    directors = models.ManyToManyField('Person', related_name='directors')

    def __unicode__(self):
        return '%s - %s' % (self.play.slug, self.show_time.strftime('%d.%b.%Y'))

    class Meta:
        ordering = ['-show_time']

    def get_playinformation(self, language):
        return self.play.playinformation_set.get(language=language)

web/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from web.models import Page, Language, Performance

def index(request, language_slug=None):
    if language_slug:
        current_language = get_object_or_404(Language, name=language_slug)
    else:
        current_language = Language.objects.all()[0]

    upcoming_performance = Performance.objects.filter(
        show_time__gte=timezone.now()
    )
    # if there's some get closest, else none
    if upcoming_performance:
        upcoming_performance = upcoming_performance.latest('show_time')
        upcoming_playinformation = upcoming_performance.get_playinformation(current_language)
    else:
        upcoming_performance = None
        upcoming_playinformation = None

    context = {
        'upcoming_performance': upcoming_performance,
        'upcoming_playinformation': upcoming_playinformation,
        'parent_pages': Page.objects.filter(parent=None),
        'languages': Language.objects.all(),
        'current_language': current_language,
    }
    return render(request, 'web/index.html', context)

def show_page(request, language_slug, page_slug):
    if language_slug:
        current_language = get_object_or_404(Language, name=language_slug)
    else:
        current_language = Language.objects.all()[0]

    page = get_object_or_404(Page,
        slug=page_slug,
        language=current_language
    )


    context = {
        'page': page,
        'parent_pages': Page.objects.filter(parent=None),
        'languages': Language.objects.all(),
        'current_language': current_language,
    }
    return render(request, 'web/show_page.html', context)

templates/web/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8">
	<title>YUĞ</title>
	<link href="{% static "css/main.css" %}" type="text/css" rel="stylesheet" />
	<link href="{% static "css/menu.css" %}" type="text/css" rel="stylesheet" />
	<link rel="icon" type="image/jpg" href="{% static "img/small_logo.jpg" %}" />
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
	<script type="text/javascript" src="{% static "js/scripts.js" %}"></script>
	
	<!--[if IE 7]>
		<style type="text/css">
			#menu li ul { margin-left: -85px; margin-top: 43px; }
			#menu-bar-right #search-label { margin-top: 4px; margin-left: -176px; }
		</style>
	<![endif]-->
	<!--[if IE 8]>
		<style type="text/css">
			#menu li ul { margin-top: 25px; }
		</style>
	<![endif]-->
	<!--[if IE 9]>
		<style type="text/css">
			#menu li ul { margin-top: 25px; }
		</style>
	<![endif]-->
</head>
<body>
	<table cellpadding="0" cellspacing="0" id="wrapper">
		<tr>
			<td id="wrapper-left"></td>
			<td id="wrapper-center">
				<div id="header">
					<a href="/{{ current_language }}" id="logo-link"></a>
					<div id="langs">
						{% for l in languages %}<a href="{{ l.get_absolute_url }}">{{ l.name|upper }}</a>{% endfor %}
					</div>
				</div>
				<div id="menu-bar">
					<ul id="menu">
						{% for p in parent_pages %}
						<li class="menu-item"><a href="{{ p.get_absolute_url }}">{{ p.title }}</a>
							{% if p.page_set.all %}
							<ul>
								{% for child in p.page_set.all %}
									<li class="menu-down-li"><a href="{{ child.get_absolute_url }}">{{ child.title }}</a></li>
								{% endfor %}
							</ul>
							{% endif %}
						</li>
						{% endfor %}
					</ul>
					<div id="menu-bar-right">
						<form action="#">
							<input id="search-box" type="text" /><label for="search-box" id="search-label">Search...</label>
						</form>
					</div>
				</div>
				<div id="content">
					{% block content %}
						
					{% endblock content %}
				</div>
				<div id="footer">
					<span>YUĞ TEATRI &copy; {% now "Y" %}</span>
				</div>
			</td>
			<td id="wrapper-right"></td>
		</tr>
		<tr>
			<td id="wrapper-bottom-left"></td>
			<td id="wrapper-bottom"></td>
			<td id="wrapper-bottom-right"></td>
		</tr>
	</table>
</body>
</html>

templates/web/index.html
{% extends "web/base.html" %}

{% load staticfiles %}
{% load thumbnail %}
{% load humanize %}

{% block content %}
<div id="content-left">
	{% if upcoming_performance %}
		{% for photo in upcoming_performance.play.playphoto_set.all %}
			<img src="{{ photo.photo.x149.url }}" alt="{{ photo.title }}" width="{{ photo.photo.x149.width }}" height="{{ photo.photo.x149.height }}" />
		{% endfor %}
	{% endif %}
</div>
<div id="content-right">
	{% if upcoming_performance %}
		<h1>{{ upcoming_playinformation.title }}</h1>
		<p>Show time: <time>{{ upcoming_performance.show_time|naturalday }}</time></p>
		<p>Actors:
		{% for actor in upcoming_performance.actors.all %}
			{{ actor.name }}{% if not forloop.last %},{% endif %}
		{% endfor %}</p>
		{% autoescape off %}
	    {{ upcoming_playinformation.body }}
		{% endautoescape %}
	{% else %}
		There're no performances.
	{% endif %}
</div>
{% endblock content %}

templates/web/show_page.html
{% extends "web/base.html" %}

{% load staticfiles %}
{% load thumbnail %}
{% load humanize %}

{% block content %}
<div class="mono-content">
	<h1>{{ page.title }}</h1>
	{% autoescape off %}
    {{ page.body }}
	{% endautoescape %}
</div>
{% endblock content %}